Create App and add Header component
gileraa/ConsciousCitizen pull request #1
Opened 2022-10-06 20:21 UTC by grusmixa

![image](https://user-images.githubusercontent.com/85351640/194410797-e3e10c62-ab4b-4508-9f85-669f670bc2cb.png)

2022-10-07 11:05 UTC, gileraa commented
Необходимо уменьшить расстояние между иконками, сделать их одинаковыми и сдвинуть к краям

2022-10-07 11:08 UTC, gileraa requested changes
Необходимо уменьшить расстояние между иконками, сделать их одинаковыми и сдвинуть к краям

2022-10-10 09:28 UTC, grusmixa commented
![image](https://user-images.githubusercontent.com/85351640/194836141-a7294842-e780-4101-8804-1a0899e7f77a.png)

2022-10-10 09:47 UTC, gileraa approved these changes
Отлично

2022-10-10 09:47 UTC, merged